-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Test_pb')


LOGINREQUEST = protobuf.Descriptor();
local LOGINREQUEST_ID_FIELD = protobuf.FieldDescriptor();
local LOGINREQUEST_INFO_FIELD = protobuf.FieldDescriptor();

LOGINREQUEST_ID_FIELD.name = "id"
LOGINREQUEST_ID_FIELD.full_name = ".LoginRequest.id"
LOGINREQUEST_ID_FIELD.number = 1
LOGINREQUEST_ID_FIELD.index = 0
LOGINREQUEST_ID_FIELD.label = 2
LOGINREQUEST_ID_FIELD.has_default_value = false
LOGINREQUEST_ID_FIELD.default_value = 0
LOGINREQUEST_ID_FIELD.type = 5
LOGINREQUEST_ID_FIELD.cpp_type = 1

LOGINREQUEST_INFO_FIELD.name = "info"
LOGINREQUEST_INFO_FIELD.full_name = ".LoginRequest.info"
LOGINREQUEST_INFO_FIELD.number = 4
LOGINREQUEST_INFO_FIELD.index = 1
LOGINREQUEST_INFO_FIELD.label = 3
LOGINREQUEST_INFO_FIELD.has_default_value = false
LOGINREQUEST_INFO_FIELD.default_value = {}
LOGINREQUEST_INFO_FIELD.type = 9
LOGINREQUEST_INFO_FIELD.cpp_type = 9

LOGINREQUEST.name = "LoginRequest"
LOGINREQUEST.full_name = ".LoginRequest"
LOGINREQUEST.nested_types = {}
LOGINREQUEST.enum_types = {}
LOGINREQUEST.fields = {LOGINREQUEST_ID_FIELD, LOGINREQUEST_INFO_FIELD}
LOGINREQUEST.is_extendable = true
LOGINREQUEST.extensions = {}

LoginRequest = protobuf.Message(LOGINREQUEST)

